# Conda environment for Gammapy version 0.10
# Install:    conda env create -f gammapy-0.10-environment.yml
# Activate:   conda activate gammapy-0.10
# Deactivate: conda deactivate

name: gammapy-0.10

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.10
  - python=3.6
  - ipython=7.2
  - jupyter=1.0
  - jupyterlab=0.35
  - pyyaml=3.13
  - click=7.0
  - numpy=1.16
  - scipy=1.2
  - pandas=0.24
  - matplotlib>=2,<3
  - astropy=3.1
  - regions=0.3
  - reproject=0.4
  - uncertainties=3.0
  - iminuit=1.3
  - sherpa=4.10
  - healpy=1.11
  - naima=0.8
